# For more info on HTTP files go to https://aka.ms/vs/httpfile
@host=http://localhost
@port=5000


//List all ToDoItems
GET {{host}}:{{port}}/api/ToDoItems

###

//Get specific ToDoItem by id
@itemToGetId = 3
GET {{host}}:{{port}}/api/ToDoItems/{{itemToGetId}}

###

//Add new ToDoItem
POST {{host}}:{{port}}/api/ToDoItems
Content-Type: application/json

{
  "name": "Example New Task 2",
  "description": "Example New Description",
  "isCompleted": false
}

###

//Update existing ToDoItem by id
@itemToUpdateId = 6

PUT {{host}}:{{port}}/api/ToDoItems/{{itemToUpdateId}}
Content-Type: application/json

{
  "name": "Updated Task 1",
  "description": "Updated Description Of Task 1",
  "isCompleted": false
}

###

//Delete exisiting ToDoItem by id
@itemToDeleteId = 1
DELETE {{host}}:{{port}}/api/ToDoItems/{{itemToDeleteId}}
